name: Scheduled Tweet

on:
  schedule:
    - cron: "0 */2 * * *"  # every 4 hours
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    env:
      X_API_KEY: ${{ secrets.X_API_KEY }}
      X_API_SECRET: ${{ secrets.X_API_SECRET }}
      X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
      NEWSDATA_KEY: ${{ secrets.NEWSDATA_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install tweepy feedparser requests beautifulsoup4

      - name: Run tweet script
        run: python tweet.py
